### ISSUE TITLE
[bug]: Ammunition prices are 1 Bulk too expensive

### ISSUE THREAD

**Issue by Cuingamehtar** [johncarney/prishas-precious-projectiles#25]
### What happened?

According to https://2e.aonprd.com/Equipment.aspx?Category=37&Subcategory=38, "To determine the Price of 10 pieces of ammunition, use the base Price for a single weapon, without adding any extra for Bulk." While the source on AoN is the old Rulebook, this is the same in GM Core pg.240.
However, current entries have the price = base + 1 Bulk
For example, low-grade silver arrows cost 44 gp per 10 arrows
Similar issue is present for other ammunition types.

### What you expected to happen

Low-grade silver arrows cost 40 gp per 10 arrows

**Comment by johncarney** [comment]
Thanks. I'd overlooked that little note about ammunition and was going on the text on page 253.

**Comment by johncarney** [comment]
Address in version 1.1.1.
