### ISSUE TITLE
Remove generic crossbow magazines

### ISSUE THREAD

**Issue by johncarney** [johncarney/prishas-precious-projectiles#5]
When we have specific magazine types for each repeating crossbow type (see issue #4 ), we should remove the generic magazines we currently have. Ideally we should offer some way to migrate existing equipment.

**Comment by TheGnome1** [comment]
probably wouldn't need to migrate existing I am sure the player will just use up the old ammo and then buy the new stuff

**Comment by johncarney** [comment]
Good point, though the ability to migrate might be useful for other situations. I can't think of any right now, so I'll consider it a "nice to have" for now :)

**Comment by johncarney** [comment]
Addressed in version 1.1.0.
